services:
    mongo:
      image: 'mongo'
      container_name: mongo
      ports:
        - '27017:27017'
      volumes:
        - ./mongo:/mongo/
      restart: always
      # PLEASE CHANGE THESE
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin

    backend:
      build: ./backend
      container_name: backend
      depends_on:
        - 'mongo'
      ports:
        - '5001:5001'
      volumes:
        - './backend:/backend/'
      environment:
        MONGODB_URI: mongodb://admin:admin@mongo:27017/admin

    frontend:
      build: ./frontend
      container_name: frontend
      depends_on:
        - backend
      ports:
        - '5173:5173'
      volumes:
        - './frontend/:/frontend/'
        - '/frontend/node_modules'
      command: npm run dev
