include:
  - ./dbs/docker-compose.dev.yml
  - ./frontend/docker-compose.dev.yml
  - ./backend/docker-compose.dev.yml

services:
  nginx:
    image: nginx:1.27.4
    volumes:
    - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: slowers-reverse-proxy-dev
    depends_on:
      - slowers-backend
      - slowers-frontend
