services:
  slowers-mongo-dev:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: default_db
    volumes: 
      - ../dbs/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ../dbs/mongo_data:/data/db
    container_name: slowers-mongo-dev
  slowers-psql-dev:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: Slowers
      POSTGRES_PASSWORD: verysecretword
    volumes: 
      - ../dbs/psql-init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: slowers-psql-dev
  server:
    image: slowers-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5001:5001
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@slowers-mongo-dev:27017/default_db
      - SECRET_KEY=tihwerei2h4rjr423ju
      - SQLDATABASEURI=postgres://Slowers:verysecretword@slowers-psql-dev:5432
    container_name: slowers-backend-dev

volumes:
  mongo_data: