kind: ImageStreamTag
apiVersion: image.openshift.io/v1
metadata:
  name: 'slowers-backend:latest'
  namespace: ohtuprojekti-staging
  uid: 0bc937a7-b692-4ebf-815c-2ba256474622
  resourceVersion: '1602020113'
  creationTimestamp: '2024-12-08T11:42:21Z'
  labels:
    app: slowers-backend
    app.kubernetes.io/component: slowers-backend
    app.kubernetes.io/instance: slowers-backend
    app.kubernetes.io/name: slowers-backend
    app.kubernetes.io/part-of: Slowers-App
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/imported-from: 'docker.io/vsirvio/slowers-backend:latest'
tag:
  name: latest
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/imported-from: 'docker.io/vsirvio/slowers-backend:latest'
  from:
    kind: DockerImage
    name: 'docker.io/vsirvio/slowers-backend:latest'
  generation: 62
  importPolicy:
    scheduled: true
    importMode: Legacy
  referencePolicy:
    type: Local
generation: 62
lookupPolicy:
  local: false
image:
  metadata:
    name: 'sha256:51cd52f67f965fa2003480af52e4d4dfde63515c1ac291c5651c849974231817'
    uid: d0bb35c6-e8c5-40cd-8a24-f8efe46db83a
    resourceVersion: '1600953218'
    creationTimestamp: '2024-12-08T11:42:21Z'
    annotations:
      image.openshift.io/dockerLayersOrder: ascending
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/imported-from: 'docker.io/vsirvio/slowers-backend:latest'
  dockerImageReference: 'image-registry.openshift-image-registry.svc:5000/ohtuprojekti-staging/slowers-backend@sha256:51cd52f67f965fa2003480af52e4d4dfde63515c1ac291c5651c849974231817'
  dockerImageMetadata:
    kind: DockerImage
    apiVersion: image.openshift.io/1.0
    Id: 'sha256:77ab4b8fba42cdf6fe9e59048adc812e8c2b2fe600390bdd498a26c257a6d24d'
    Created: '2024-12-08T11:35:09Z'
    ContainerConfig: {}
    Config:
      ExposedPorts:
        5001/tcp: {}
      Env:
        - 'PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
        - GOLANG_VERSION=1.23.4
        - GOTOOLCHAIN=local
        - GOPATH=/go
      Cmd:
        - /bin/sh
        - '-c'
        - ./start-server
      WorkingDir: /app
    Architecture: amd64
    Size: 464941401
  dockerImageMetadataVersion: '1.0'
  dockerImageLayers:
    - name: 'sha256:fdf894e782a221820acf469d425b802be26aedb5e5d26ea80a650ff6a974d488'
      size: 48497210
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:5bd71677db44bb63b94de61b6f1f95d5540b4ba2d6a8a6bc4d19f422b25e0c2b'
      size: 23865876
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:551df7f94f9c131f2fec0e8063142411365f0a1c88b935b9fac22be91af227e0'
      size: 64391508
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:12b0926ac04261a9a8a0b1af4f4ed4b58b6374e3b6933d877c0659c294ea7576'
      size: 92312289
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:06f05ace1117d62b655e04f6f73c83617e3e0febc38681dbedf58f477dd0658c'
      size: 74047449
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:f931ef26d2833f529085c8141e621cf72a1277f6524c25ae5550a255ee4c5b01'
      size: 125
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1'
      size: 32
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:a5cfbb98af41cf7a4f2639848d1ba0ccfbb28d9dc2bb2768f8e074312f6892c9'
      size: 93
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:48e98a2b761ad1fa82d15c9fb547cd1e7e2725e2a78f787cb4a63dc9cb9c37ce'
      size: 23712
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
    - name: 'sha256:7bada7827820b527ef98029bd8b0c08710ee31d251c8698fec6462bd96cd0752'
      size: 161799331
      mediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  dockerImageManifestMediaType: application/vnd.docker.distribution.manifest.v2+json
