services:
  slowers-mongo-dev:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .dev.env
    volumes: 
      - ../dbs/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ../dbs/mongo_data:/data/db
    container_name: slowers-mongo-dev
  slowers-psql-dev:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .dev.env
    volumes: 
      - ../dbs/psql-init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: slowers-psql-dev

volumes:
  mongo_data:
