services:
  slowers-mongo-dev:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .dev.env
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
    container_name: slowers-mongo-dev
  slowers-psql-dev:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .dev.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - ./psql_data:/var/lib/postgresql/data
    container_name: slowers-psql-dev

volumes:
  mongo_data:
  psql_data:
