name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.runCommand({ping: 1}).ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.23'

    - name: Install Mockery
      run: sudo go install github.com/vektra/mockery/v2@v2.46.3
      env:
        GOBIN: ${{ env.GITHUB_WORKSPACE }}/go/bin

    - name: Generate mocks
      run: ${{ env.GITHUB_WORKSPACE }}/go/bin/mockery
      working-directory: backend

    - name: Backend unit tests
      run: go test ./...
      working-directory: backend
      env:
        MONGODB_URI: mongodb://localhost:27017
        SECRET_KEY: secretkey
