name: Staging

on:
  push:
    branches: [development]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the backend Docker image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/slowers-backend:latest

      - name: Build and push the frontend Docker image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/slowers-frontend:latest
